# Changes here will be overwritten by Copier
_commit: v0.0.12
_src_path: gh:AmpelAstro/copier-ampel
author_email: jakob.van.santen@desy.de
author_name: Jakob van Santen
plugin_description: Astronomy units for the Ampel system from HU-Berlin
plugin_name: HU-astro
plugin_org: AmpelAstro
plugin_version: 0.10.0a14
version_cap: <0.11
