pipeline {
  agent none
  stages {
    stage('build') {
      agent {
        dockerfile {
          filename '.jenkins/Dockerfile.build'
        }
      }
      steps {
        sh 'ampel-config build -v >/dev/null'
        sh 'rm mypy.*.xml || true'
        sh 'run_mypy.sh ampel'
      }
      post {
        always {
          junit 'mypy.*.xml'
        }
      }
    }
  }
}
