pipeline {
  agent none
  stages {
    stage('dependencies') {
      agent any
      steps {
          dir(path: '.jenkins/Ampel-interface') {
            git(url: 'https://github.com/AmpelProject/Ampel-interface', credentialsId: 'github')
          }
          dir(path: '.jenkins/Ampel-core') {
            git(url: 'https://github.com/AmpelProject/Ampel-core', credentialsId: 'github')
          }
          dir(path: '.jenkins/Ampel-photometry') {
            git(url: 'https://github.com/AmpelProject/Ampel-photometry', credentialsId: 'github')
          }
          dir(path: '.jenkins/Ampel-alerts') {
            git(url: 'https://github.com/AmpelProject/Ampel-alerts', credentialsId: 'github')
          }
          dir(path: '.jenkins/Ampel-ZTF') {
            git(url: 'https://github.com/AmpelProject/Ampel-ZTF', credentialsId: 'github')
          }
          dir(path: '.jenkins/Ampel-contrib-ZTFbh') {
            git(url: 'https://github.com/robertdstein/Ampel-contrib-ZTFbh.git', branch: 'v0.7', credentialsId: 'github')
          }
      }
    }
    stage('build') {
      agent {
        dockerfile {
          filename '.jenkins/Dockerfile.build'
        }
      }
      steps {
        sh 'ampel-config build -v >/dev/null'
        sh 'rm mypy.*.xml || true'
        sh 'run_mypy.sh ampel'
      }
      post {
        always {
          junit 'mypy.*.xml'
        }
      }
    }
  }
}
